version: '3.4'

services:
  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    container_name: ametista-mssql
    volumes:
      - mssql_server_data:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: Express
      SA_PASSWORD: MyPassword123456
    ports:
      - "1433:1433"

  nosql.data:
    container_name: ametista-mongodb
    image: mongo:latest
    ports:
      - "27017:27017"  # Important: In a production environment your should remove the external port

  rabbitmq:
    container_name: ametista-rabbitmq
    image: rabbitmq:3.7.7-management-alpine
    ports:
      - "15672:15672"  # Important: In a production environment your should remove the external port
      - "5672:5672"    # Important: In a production environment your should remove the external port
  
  redis.cache:
    container_name: ametista-redis
    image: redis:alpine
    ports:
      - "6379:6379"

  ametista.api:
    container_name: ametista-api
    image: ametistaapi
    build:
      context: .
      dockerfile: Ametista.Api/Dockerfile
    depends_on:
      - mssql
      - rabbitmq
      - nosql.data
      - redis.cache
    ports:
      - "5101:80"

volumes:
  mssql_server_data: